package certificates

import (
	"context"
	"io"
	"testing"
	"time"

	domaincerts "lms-backend/internal/domain/certificates"
	"lms-backend/internal/domain/notifications"

	"github.com/google/uuid"
	"pgregory.net/rapid"
)

// ─── Mock implementations ────────────────────────────────────────────────────

// mockCertificateRepo implements domaincerts.CertificateRepository
type mockCertificateRepo struct {
	certs           []*domaincerts.Certificate
	byStudentCourse map[[2]uuid.UUID]*domaincerts.Certificate
	byVerification  map[string]*domaincerts.Certificate
}

func newMockCertificateRepo() *mockCertificateRepo {
	return &mockCertificateRepo{
		certs:           make([]*domaincerts.Certificate, 0),
		byStudentCourse: make(map[[2]uuid.UUID]*domaincerts.Certificate),
		byVerification:  make(map[string]*domaincerts.Certificate),
	}
}

func (m *mockCertificateRepo) Create(ctx context.Context, cert *domaincerts.Certificate) error {
	m.certs = append(m.certs, cert)
	m.byStudentCourse[[2]uuid.UUID{cert.StudentID, cert.CourseID}] = cert
	m.byVerification[cert.VerificationID] = cert
	return nil
}

func (m *mockCertificateRepo) FindByStudentAndCourse(ctx context.Context, studentID, courseID uuid.UUID) (*domaincerts.Certificate, error) {
	cert, ok := m.byStudentCourse[[2]uuid.UUID{studentID, courseID}]
	if !ok {
		return nil, nil
	}
	return cert, nil
}

func (m *mockCertificateRepo) FindByVerificationID(ctx context.Context, verificationID string) (*domaincerts.Certificate, error) {
	cert, ok := m.byVerification[verificationID]
	if !ok {
		return nil, nil
	}
	return cert, nil
}

func (m *mockCertificateRepo) UpdatePDFKey(ctx context.Context, id uuid.UUID, pdfKey string) error {
	for _, cert := range m.certs {
		if cert.ID == id {
			cert.PDFRustFSKey = &pdfKey
			return nil
		}
	}
	return nil
}

// mockJobQueue implements notifications.JobQueue
type mockJobQueue struct {
	jobs []notifications.Job
}

func (m *mockJobQueue) Enqueue(ctx context.Context, job notifications.Job) error {
	m.jobs = append(m.jobs, job)
	return nil
}

func (m *mockJobQueue) Dequeue(ctx context.Context, timeout time.Duration) (*notifications.Job, error) {
	if len(m.jobs) == 0 {
		return nil, nil
	}
	job := m.jobs[0]
	m.jobs = m.jobs[1:]
	return &job, nil
}

// mockStorageClient implements StorageClient
type mockStorageClient struct{}

func (m *mockStorageClient) PutObject(ctx context.Context, bucket, key string, r io.Reader, size int64, contentType string) error {
	return nil
}

func (m *mockStorageClient) PresignGetURL(ctx context.Context, bucket, key string, ttl time.Duration) (string, error) {
	return "https://example.com/presigned/" + key, nil
}

// ─── Helper: build a service with all mocks ──────────────────────────────────

type certPropDeps struct {
	certRepo *mockCertificateRepo
	jobQueue *mockJobQueue
	storage  *mockStorageClient
}

func newCertPropDeps() *certPropDeps {
	return &certPropDeps{
		certRepo: newMockCertificateRepo(),
		jobQueue: &mockJobQueue{},
		storage:  &mockStorageClient{},
	}
}

func (d *certPropDeps) service() Service {
	return NewService(
		d.certRepo,
		d.jobQueue,
		d.storage,
		nil, // PDFRenderer not needed for these properties
		"lms-certificates",
	)
}

// ─── Property 50 ─────────────────────────────────────────────────────────────

// TestProperty50_CertificateAutoGeneratedAt100PercentCompletion verifies that
// AutoGenerateCertificate creates a Certificate record with a unique verification_id
// when a student reaches 100% course completion.
//
// **Validates: Requirements 18.1**
func TestProperty50_CertificateAutoGeneratedAt100PercentCompletion(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		deps := newCertPropDeps()
		svc := deps.service()
		ctx := context.Background()

		studentID := uuid.New()
		courseID := uuid.New()

		studentName := rapid.StringMatching(`[A-Za-z ]{2,50}`).Draw(t, "student_name")
		courseTitle := rapid.StringMatching(`[A-Za-z ]{2,50}`).Draw(t, "course_title")
		instructorName := rapid.StringMatching(`[A-Za-z ]{2,50}`).Draw(t, "instructor_name")

		cmd := AutoGenerateCertificateCommand{
			StudentID:      studentID,
			CourseID:       courseID,
			StudentName:    studentName,
			CourseTitle:    courseTitle,
			InstructorName: instructorName,
		}

		// Trigger certificate generation (simulates 100% progress reached)
		result, err := svc.AutoGenerateCertificate(ctx, cmd)
		if err != nil {
			t.Fatalf("AutoGenerateCertificate failed: %v", err)
		}

		// Property: a certificate record must be created
		if result == nil {
			t.Fatal("expected a certificate response, got nil")
		}

		// Property: verification_id must be non-empty and exactly 64 hex chars
		if len(result.VerificationID) != 64 {
			t.Fatalf("verification_id must be 64 chars, got %d: %q", len(result.VerificationID), result.VerificationID)
		}

		// Property: snapshots must match the command inputs
		if result.StudentName != studentName {
			t.Fatalf("student_name snapshot mismatch: want %q, got %q", studentName, result.StudentName)
		}
		if result.CourseTitle != courseTitle {
			t.Fatalf("course_title snapshot mismatch: want %q, got %q", courseTitle, result.CourseTitle)
		}
		if result.InstructorName != instructorName {
			t.Fatalf("instructor_name snapshot mismatch: want %q, got %q", instructorName, result.InstructorName)
		}

		// Property: exactly one certificate record must exist in the repo
		if len(deps.certRepo.certs) != 1 {
			t.Fatalf("expected exactly 1 certificate in repo, got %d", len(deps.certRepo.certs))
		}

		// Property: the certificate must be retrievable by student+course
		stored, err := deps.certRepo.FindByStudentAndCourse(ctx, studentID, courseID)
		if err != nil || stored == nil {
			t.Fatal("certificate must be retrievable by student+course after creation")
		}
		if stored.VerificationID != result.VerificationID {
			t.Fatalf("stored verification_id %q does not match returned %q", stored.VerificationID, result.VerificationID)
		}

		// Property: a generate_certificate job must be enqueued
		if len(deps.jobQueue.jobs) != 1 {
			t.Fatalf("expected 1 job enqueued, got %d", len(deps.jobQueue.jobs))
		}
		if deps.jobQueue.jobs[0].Type != "generate_certificate" {
			t.Fatalf("expected job type 'generate_certificate', got %q", deps.jobQueue.jobs[0].Type)
		}

		// Property: calling AutoGenerateCertificate again for the same student+course
		// must be idempotent — no duplicate certificate created
		result2, err := svc.AutoGenerateCertificate(ctx, cmd)
		if err != nil {
			t.Fatalf("second AutoGenerateCertificate failed: %v", err)
		}
		if result2.VerificationID != result.VerificationID {
			t.Fatalf("idempotent call must return same verification_id: want %q, got %q", result.VerificationID, result2.VerificationID)
		}
		if len(deps.certRepo.certs) != 1 {
			t.Fatalf("idempotent call must not create a second certificate, got %d", len(deps.certRepo.certs))
		}

		// Property: different student+course pairs must get different verification_ids
		deps2 := newCertPropDeps()
		svc2 := deps2.service()
		differentStudentID := uuid.New()
		result3, err := svc2.AutoGenerateCertificate(ctx, AutoGenerateCertificateCommand{
			StudentID:      differentStudentID,
			CourseID:       courseID,
			StudentName:    studentName,
			CourseTitle:    courseTitle,
			InstructorName: instructorName,
		})
		if err != nil {
			t.Fatalf("AutoGenerateCertificate for different student failed: %v", err)
		}
		if result3.VerificationID == result.VerificationID {
			t.Fatal("different student+course must produce a different verification_id")
		}
	})
}

// ─── Property 51 ─────────────────────────────────────────────────────────────

// TestProperty51_CertificateVerificationRoundTrip verifies that for any valid
// Certificate record, VerifyCertificate returns valid: true and the correct
// public fields.
//
// **Validates: Requirements 18.6**
func TestProperty51_CertificateVerificationRoundTrip(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		deps := newCertPropDeps()
		svc := deps.service()
		ctx := context.Background()

		// Generate 1–5 certificates
		numCerts := rapid.IntRange(1, 5).Draw(t, "num_certs")

		type certInfo struct {
			studentID      uuid.UUID
			courseID       uuid.UUID
			studentName    string
			courseTitle    string
			instructorName string
			verificationID string
		}

		issuedCerts := make([]certInfo, 0, numCerts)

		for i := 0; i < numCerts; i++ {
			studentID := uuid.New()
			courseID := uuid.New()
			studentName := rapid.StringMatching(`[A-Za-z ]{2,30}`).Draw(t, "student_name")
			courseTitle := rapid.StringMatching(`[A-Za-z ]{2,30}`).Draw(t, "course_title")
			instructorName := rapid.StringMatching(`[A-Za-z ]{2,30}`).Draw(t, "instructor_name")

			result, err := svc.AutoGenerateCertificate(ctx, AutoGenerateCertificateCommand{
				StudentID:      studentID,
				CourseID:       courseID,
				StudentName:    studentName,
				CourseTitle:    courseTitle,
				InstructorName: instructorName,
			})
			if err != nil {
				t.Fatalf("AutoGenerateCertificate failed for cert %d: %v", i, err)
			}

			issuedCerts = append(issuedCerts, certInfo{
				studentID:      studentID,
				courseID:       courseID,
				studentName:    studentName,
				courseTitle:    courseTitle,
				instructorName: instructorName,
				verificationID: result.VerificationID,
			})
		}

		// Property: for every issued certificate, VerifyCertificate must return valid: true
		for _, info := range issuedCerts {
			verifyResult, err := svc.VerifyCertificate(ctx, VerifyCertificateCommand{
				VerificationID: info.verificationID,
			})
			if err != nil {
				t.Fatalf("VerifyCertificate failed for verification_id %q: %v", info.verificationID, err)
			}
			if !verifyResult.Valid {
				t.Fatalf("VerifyCertificate must return valid: true for issued certificate %q", info.verificationID)
			}

			// Property: public fields must match the issued certificate
			if verifyResult.VerificationID != info.verificationID {
				t.Fatalf("verification_id mismatch: want %q, got %q", info.verificationID, verifyResult.VerificationID)
			}
			if verifyResult.StudentName != info.studentName {
				t.Fatalf("student_name mismatch: want %q, got %q", info.studentName, verifyResult.StudentName)
			}
			if verifyResult.CourseTitle != info.courseTitle {
				t.Fatalf("course_title mismatch: want %q, got %q", info.courseTitle, verifyResult.CourseTitle)
			}
			if verifyResult.InstructorName != info.instructorName {
				t.Fatalf("instructor_name mismatch: want %q, got %q", info.instructorName, verifyResult.InstructorName)
			}
			if verifyResult.IssuedAt.IsZero() {
				t.Fatal("issued_at must not be zero")
			}
		}

		// Property: an unknown verification_id must return valid: false
		unknownID := "0000000000000000000000000000000000000000000000000000000000000000"
		invalidResult, err := svc.VerifyCertificate(ctx, VerifyCertificateCommand{
			VerificationID: unknownID,
		})
		if err != nil {
			t.Fatalf("VerifyCertificate for unknown ID failed: %v", err)
		}
		if invalidResult.Valid {
			t.Fatal("VerifyCertificate must return valid: false for unknown verification_id")
		}

		// Property: pdf_rustfs_key must never appear in the VerifyCertificate response
		// (verified by the fact that VerifyCertificateResponse has no pdf_rustfs_key field)
		// This is enforced at compile time by the response struct definition.

		// Property: completion_date must be a valid date string (YYYY-MM-DD)
		for _, info := range issuedCerts {
			verifyResult, _ := svc.VerifyCertificate(ctx, VerifyCertificateCommand{
				VerificationID: info.verificationID,
			})
			if _, err := time.Parse("2006-01-02", verifyResult.CompletionDate); err != nil {
				t.Fatalf("completion_date %q is not a valid YYYY-MM-DD date: %v", verifyResult.CompletionDate, err)
			}
		}
	})
}
